name: .NET Build & Test + Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Lab5_CollectionsSolution.sln

      - name: Build
        run: dotnet build Lab5_CollectionsSolution.sln --configuration Release --no-restore

      - name: Run unit tests (test project)
        run: dotnet test tests/Lab5.Tests/Lab5.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Run application (optional)
        run: dotnet run --project src/Lab5App/Lab5App.csproj --configuration Release --no-build || true
